// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safiya.Hossam._0523049.Db;

#nullable disable

namespace Safiya.Hossam._0523049.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<int>("competitionsId")
                        .HasColumnType("int");

                    b.Property<int>("teamsId")
                        .HasColumnType("int");

                    b.HasKey("competitionsId", "teamsId");

                    b.HasIndex("teamsId");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specilazation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coachs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceYears = 5,
                            Name = "Safiya",
                            Specilazation = "FootBall"
                        },
                        new
                        {
                            Id = 2,
                            ExperienceYears = 3,
                            Name = "mana",
                            Specilazation = "kasbd"
                        },
                        new
                        {
                            Id = 3,
                            ExperienceYears = 2,
                            Name = "Sara",
                            Specilazation = "poiq"
                        });
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2008, 9, 11),
                            Location = "TRRVS",
                            Name = "Isef"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2022, 9, 21),
                            Location = "AXD",
                            Name = "ProbSolve"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 8, 10),
                            Location = "TRRVS",
                            Name = "Isef"
                        });
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 18,
                            FullName = "NourMohamed",
                            Position = "La3epMarma",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 17,
                            FullName = "OmarAhmed",
                            Position = "Attacker",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            FullName = "MazenYousef",
                            Position = "Modafe3",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ciy = "Giza",
                            CoachId = 1,
                            Name = "MRT"
                        },
                        new
                        {
                            Id = 2,
                            Ciy = "Warraq",
                            CoachId = 2,
                            Name = "SEQ"
                        },
                        new
                        {
                            Id = 3,
                            Ciy = "Giza",
                            CoachId = 3,
                            Name = "CRT"
                        });
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("Safiya.Hossam._0523049.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("competitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safiya.Hossam._0523049.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("teamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Player", b =>
                {
                    b.HasOne("Safiya.Hossam._0523049.Models.Team", "Team")
                        .WithMany("players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Team", b =>
                {
                    b.HasOne("Safiya.Hossam._0523049.Models.Coach", "Coach")
                        .WithOne("Team")
                        .HasForeignKey("Safiya.Hossam._0523049.Models.Team", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Coach", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("Safiya.Hossam._0523049.Models.Team", b =>
                {
                    b.Navigation("players");
                });
#pragma warning restore 612, 618
        }
    }
}
